name: Run Checks

on:
  pull_request:
    branches:
      - main

permissions:
  actions: write
  contents: read
  checks: write

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.ci.txt
      - name: Install NodeJS dependencies
        run: npm ci
      - name: Lint Python source
        run: |
          ruff check --format=github --select=E9,F63,F7,F82 --target-version=py311 .
